name: GraphQLStandardSchema
on:
   push:

permissions: # added using https://github.com/step-security/secure-repo
   contents: read

jobs:
   gqlstdschema:
      runs-on: ubuntu-latest
      steps:
         - name: Harden the runner (Audit all outbound calls)
           uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
           with:
              egress-policy: audit
         - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
         - uses: denoland/setup-deno@909cc5acb0fdd60627fb858598759246509fa755 # v2.0.2
           with:
              deno-version: '2.1.9'
         - name: Cache https://
           uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
           with:
              path: ~/.cache/deno/deps/https
              key: deno-https/v1-${{ github.sha }}
              restore-keys: deno-https/v1-
         - run: deno task lint
         - run: deno task coverage
         - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
           with:
              node-version: '22.x'
              registry-url: 'https://registry.npmjs.org'
         - name: Build and test npm module
           run: deno task dnt
